# Generated by Django 4.2.22 on 2025-06-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='region',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='idComuna',
        ),
        migrations.RemoveField(
            model_name='usuariocustom',
            name='idComuna',
        ),
        migrations.DeleteModel(
            name='comuna',
        ),
        migrations.DeleteModel(
            name='region',
        ),
    ]
